### ISSUE TITLE
Zigbee2MQTT error after deployment

### ISSUE THREAD

**Issue by kathodion** [OliverHi/smarthomeserver#3]
zigbee2mqtt           | Zigbee2MQTT:info  2022-12-27 12:15:20: Starting Zigbee2MQTT version 1.28.4 (commit #52e545f)
zigbee2mqtt           | Zigbee2MQTT:info  2022-12-27 12:15:20: Starting zigbee-herdsman (0.14.76)
zigbee2mqtt           | Zigbee2MQTT:info  2022-12-27 12:15:21: zigbee-herdsman started (resumed)
zigbee2mqtt           | Zigbee2MQTT:info  2022-12-27 12:15:21: Coordinator firmware version: '{"meta":{"maintrel":0,"majorrel":38,"minorrel":114,"product":0,"revision":"0x26720700","transportrev":0},"type":"ConBee2/RaspBee2"}'
zigbee2mqtt           | Zigbee2MQTT:info  2022-12-27 12:15:21: Currently 0 devices are joined:
zigbee2mqtt           | Zigbee2MQTT:warn  2022-12-27 12:15:21: `permit_join` set to  `true` in configuration.yaml.
zigbee2mqtt           | Zigbee2MQTT:warn  2022-12-27 12:15:21: Allowing new devices to join.
zigbee2mqtt           | Zigbee2MQTT:warn  2022-12-27 12:15:21: Set `permit_join` to `false` once you joined all devices.
zigbee2mqtt           | Zigbee2MQTT:info  2022-12-27 12:15:21: Zigbee: allowing new devices to join.
zigbee2mqtt           | Zigbee2MQTT:info  2022-12-27 12:15:22: Connecting to MQTT server at mqtt://localhost
zigbee2mqtt           | Zigbee2MQTT:error 2022-12-27 12:15:22: MQTT error: connect ECONNREFUSED 127.0.0.1:1883
zigbee2mqtt           | Zigbee2MQTT:error 2022-12-27 12:15:22: MQTT failed to connect, exiting...
zigbee2mqtt           | Zigbee2MQTT:info  2022-12-27 12:15:22: Stopping zigbee-herdsman...
zigbee2mqtt           | Zigbee2MQTT:error 2022-12-27 12:15:23: MQTT error: connect ECONNREFUSED 127.0.0.1:1883
zigbee2mqtt           | Zigbee2MQTT:info  2022-12-27 12:15:23: Stopped zigbee-herdsman
[README.md](https://github.com/OliverHi/smarthomeserver/files/10307785/README.md)

[smarthomeserver.zip](https://github.com/OliverHi/smarthomeserver/files/10307787/smarthomeserver.zip)

**env file**
````
# general
DATADIR=/dockerData
TZ=Europe/Berlin
PUID=1000
PGID=1000
EMAIL_FROM=senderemail@yourserver.net
SMTP_SERVER=smtp.yourserver.net
SMTP_PORT=587
SMTP_USER=username
SMTP_PASSWORD=password123

# pihole
PH_WEBPASSWORD=password123

# watchtower
WATCHTOWER_EMAIL_TO=receiveremail@yourserver.net

# pushover (used with watchtower)
PO_USERKEY=abc123
PO_TOKEN=def456
````

zigbee2mqtt_configuration.yaml
````
# example config for usage with the Sonoff Zbridge controller and Home Assistant
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.2.4 # your mqtt broker IP
serial:
  port: tcp://192.168.3.6:8888 # IP of your Zigbee bridge
  adapter: ezsp
# alternative with USB connection
#serial:  
#  port: /dev/ttyUSB0
frontend: true
advanced:
  network_key: GENERATE # generates a new key on first start and automatically replaces this
````

mosquitto.conf
````
pid_file /var/run/mosquitto.pid

persistence true
persistence_location /mosquitto/data/

log_dest file /mosquitto/log/mosquitto.log

port 1883
listener 9001
protocol websockets
````

**Comment by OliverHi** [comment]
Hi, a short description of what you have tried so far would be helpful! From the log `Connecting to MQTT server at mqtt://localhost` I can see that most likely you have not shared your actual configuration here but instead pointed Zigbee2MQTT to localhost to find the MQTT server. This won't work as in this setup they are not actually running on the same machine but on different Docker containers.
If you are using my setup file here try it with either `mqtt://mosquitto` (uses the MQTT brokers container name) or the IP of your server like `mqtt://192.168.2.4` for example in the zigbee2mqtt configuration and check the logs to see if mosquitto did actually start up properly.

**Comment by kathodion** [comment]
> Hi, a short description of what you have tried so far would be helpful! From the log `Connecting to MQTT server at mqtt://localhost` I can see that most likely you have not shared your actual configuration here but instead pointed Zigbee2MQTT to localhost to find the MQTT server. This won't work as in this setup they are not actually running on the same machine but on different Docker containers. If you are using my setup file here try it with either `mqtt://mosquitto` (uses the MQTT brokers container name) or the IP of your server like `mqtt://192.168.2.4` for example in the zigbee2mqtt configuration and check the logs to see if mosquitto did actually start up properly.

Thank you @OliverHi 
I will have a look later. I was confused about the server ip setting part.
````
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.2.4 # your mqtt broker IP
````
What IP I should use. Because I have all services in one compose file (grafana, influx, mqtt, mosquitto etc.)

Give a Update here later

**Comment by kathodion** [comment]
```
Using '/app/data' as data directory
Zigbee2MQTT:info  2022-12-28 13:07:53: Logging to console and directory: '/app/data/log/2022-12-28.13-07-53' filename: log.txt
Zigbee2MQTT:info  2022-12-28 13:07:53: Starting Zigbee2MQTT version 1.28.4 (commit #52e545f)
Zigbee2MQTT:info  2022-12-28 13:07:53: Starting zigbee-herdsman (0.14.76)
Zigbee2MQTT:info  2022-12-28 13:07:54: zigbee-herdsman started (resumed)
Zigbee2MQTT:info  2022-12-28 13:07:54: Coordinator firmware version: '{"meta":{"maintrel":0,"majorrel":38,"minorrel":114,"product":0,"revision":"0x26720700","transportrev":0},"type":"ConBee2/RaspBee2"}'
Zigbee2MQTT:info  2022-12-28 13:07:54: Currently 0 devices are joined:
Zigbee2MQTT:warn  2022-12-28 13:07:54: `permit_join` set to  `true` in configuration.yaml.
Zigbee2MQTT:warn  2022-12-28 13:07:54: Allowing new devices to join.
Zigbee2MQTT:warn  2022-12-28 13:07:54: Set `permit_join` to `false` once you joined all devices.
Zigbee2MQTT:info  2022-12-28 13:07:54: Zigbee: allowing new devices to join.
Zigbee2MQTT:info  2022-12-28 13:07:55: Connecting to MQTT server at mqtt://localhost
Zigbee2MQTT:error 2022-12-28 13:07:55: MQTT error: connect ECONNREFUSED 127.0.0.1:1883
Zigbee2MQTT:error 2022-12-28 13:07:55: MQTT failed to connect, exiting...
Zigbee2MQTT:info  2022-12-28 13:07:55: Stopping zigbee-herdsman...
Zigbee2MQTT:error 2022-12-28 13:07:56: MQTT error: connect ECONNREFUSED 127.0.0.1:1883
Zigbee2MQTT:info  2022-12-28 13:07:57: Stopped zigbee-herdsman
Using '/app/data' as data directory
```

dump from the Zigbee2MQTT container. I think the container does not pick up the container config.

docker compose part of Zigbee2MQTT 
```
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    depends_on:
      mosquitto:
        condition: service_started
    restart: unless-stopped
    ports:
      - 6090:8080 # if you enabled the web UI
    volumes:
      - ${DATADIR}/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyACM0:/dev/ttyACM0 # or whichever port your Zigbee stick is connected to
    environment:
      - TZ=${TZ}
```

zigbee2mqtt config file
```
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://172.18.0.6 # your mqtt broker IP
serial:  
 port: /dev/ttyACM0
frontend: true
advanced:
  network_key: GENERATE # generates a new key on first start and automatically replaces this
```

compose logs
[myDockerCompose.log](https://github.com/OliverHi/smarthomeserver/files/10314154/myDockerCompose.log)


How do I tell zigbee2mqtt to grab which config file?

**Comment by kathodion** [comment]
´´´´
Using '/app/data' as data directory
Zigbee2MQTT:info  2022-12-28 13:07:53: Logging to console and directory: '/app/data/log/2022-12-28.13-07-53' filename: log.txt
Zigbee2MQTT:info  2022-12-28 13:07:53: Starting Zigbee2MQTT version 1.28.4 (commit #52e545f)
Zigbee2MQTT:info  2022-12-28 13:07:53: Starting zigbee-herdsman (0.14.76)
Zigbee2MQTT:info  2022-12-28 13:07:54: zigbee-herdsman started (resumed)
Zigbee2MQTT:info  2022-12-28 13:07:54: Coordinator firmware version: '{"meta":{"maintrel":0,"majorrel":38,"minorrel":114,"product":0,"revision":"0x26720700","transportrev":0},"type":"ConBee2/RaspBee2"}'
Zigbee2MQTT:info  2022-12-28 13:07:54: Currently 0 devices are joined:
Zigbee2MQTT:warn  2022-12-28 13:07:54: `permit_join` set to  `true` in configuration.yaml.
Zigbee2MQTT:warn  2022-12-28 13:07:54: Allowing new devices to join.
Zigbee2MQTT:warn  2022-12-28 13:07:54: Set `permit_join` to `false` once you joined all devices.
Zigbee2MQTT:info  2022-12-28 13:07:54: Zigbee: allowing new devices to join.
Zigbee2MQTT:info  2022-12-28 13:07:55: Connecting to MQTT server at mqtt://localhost
Zigbee2MQTT:error 2022-12-28 13:07:55: MQTT error: connect ECONNREFUSED 127.0.0.1:1883
Zigbee2MQTT:error 2022-12-28 13:07:55: MQTT failed to connect, exiting...
Zigbee2MQTT:info  2022-12-28 13:07:55: Stopping zigbee-herdsman...
Zigbee2MQTT:error 2022-12-28 13:07:56: MQTT error: connect ECONNREFUSED 127.0.0.1:1883
Zigbee2MQTT:info  2022-12-28 13:07:57: Stopped zigbee-herdsman
Using '/app/data' as data directory
´´´´

dump from the Zigbee2MQTT container. I think the container does not pick up the container config.

docker compose part of Zigbee2MQTT 
´´´´
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    depends_on:
      mosquitto:
        condition: service_started
    restart: unless-stopped
    ports:
      - 6090:8080 # if you enabled the web UI
    volumes:
      - ${DATADIR}/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyACM0:/dev/ttyACM0 # or whichever port your Zigbee stick is connected to
    environment:
      - TZ=${TZ}
´´´´

zigbee2mqtt config file
´´´´
# example config for usage with the Sonoff Zbridge controller and Home Assistant
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://172.18.0.6 # your mqtt broker IP
serial:  
 port: /dev/ttyACM0
frontend: true
advanced:
  network_key: GENERATE # generates a new key on first start and automatically replaces this
´´´´
compose logs
[myDockerCompose.log](https://github.com/OliverHi/smarthomeserver/files/10314154/myDockerCompose.log)


How do I tell zigbee2mqtt to grab which config file?

**Comment by OliverHi** [comment]
Your Zigbee container is using the shared folder `- ${DATADIR}/zigbee2mqtt:/app/data` so you should check `${DATADIR}/zigbee2mqtt` on your file system. Move a file called configuration.yaml with the content of your zigbee2mqtt config file there and restart the container. It should now use the configurations from this file.
If all containers are in the same yaml file then using `mqtt://mosquitto` as a server name in the config should work.

**Comment by kathodion** [comment]
> Your Zigbee container is using the shared folder `- ${DATADIR}/zigbee2mqtt:/app/data` so you should check `${DATADIR}/zigbee2mqtt` on your file system. Move a file called configuration.yaml with the content of your zigbee2mqtt config file there and restart the container. It should now use the configurations from this file. If all containers are in the same yaml file then using `mqtt://mosquitto` as a server name in the config should work.

at first thank you @OliverHi for your support.

I got my containers running with your help and some other resource.
I also update my conbee2 to the latest firmware - this might also be an issue.

This setup works for me now

zigbee2mqtt yml
```
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: always
    # ports:
    #   - 6090:8080 # if you enabled the web UI
    volumes:
      - ${DATADIR}/zigbee2mqtt/data:/app/data/
      # - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyACM0:/dev/ttyACM0 # or whichever port your Zigbee stick is connected to
    environment:
      - TZ=${TZ}
    depends_on:
      - mosquitto
    network_mode: host
```
zigbee2mqtt config file
```
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.0.177:2800
  client_id: zigbee2mqtt
  include_device_information: true
frontend: true
serial:
  port: /dev/ttyACM0
  disable_led: false
  adapter: deconz
advanced:
  homeassistant_discovery_topic: homeassistant
```
mosquito yml
```
  mosquito:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: unless-stopped
    volumes:
      - "${DATADIR}/mosquitto:/mosquitto/config"
      - "${DATADIR}/mosquitto:/mosquitto/data"
      - "${DATADIR}/mosquitto:/mosquitto/log"
    ports:
      - 2800:2800
      - 9100:9100
    stdin_open: true
    tty: true
volumes:
  config:
  data:
  log:
```
mosquito config file
```
persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
allow_anonymous true
# password_file /mosquitto/config/pwfile
listener 2800
listener 9100
protocol websockets
```
